engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
    	standard: "PSR1,PSR2"
  phan:
    enabled: true
    config:
      file_extensions: "php"
ratings:
  paths:
  - "src/**"
exclude_paths: []